// get all gamers
GET http://localhost:4300/api/v1/gamer/

###
// get all gamers
GET https://planet-virtron-api-production.up.railway.app/api/v1/gamer/

###
// get all accounts
GET http://localhost:4300/api/v1/account

###
// create a new account 
POST http://localhost:4300/api/v1/account/
Content-Type: application/json

###
// add account to gamer
POST http://localhost:4300/api/v1/gamer/add-account
Content-Type: application/json

{
  "gamerTag": "Lamar",
  "accountId": "6527d693ac863aeecd5eede9"
}

###
// initialize VRT coin
POST http://localhost:4300/api/v1/vrt
Content-Type: application/json

###
// create new block
POST http://localhost:4300/api/v1/block
Content-Type: application/json

###
// transfer VRT coin
POST http://localhost:4300/api/v1/transaction/transfer
Content-Type: application/json

{
  "senderPublicKey": "5ubXf3orDt44tZ3Kd3fQxnhkPhYkKG5cWFA74tVvyAfW", 
  "recipientPublicKey": "3wUBnsHUaaZBUKw5CBp6RNpxFrgxBQeJB4gUyapsMYnx", 
  "amount": "25", 
  "privateKey": "h5ZoEaUXsPP3WNNi3GugVM7TpuLpCZcvACuEyX9PHoZ9mLgjpATsk7Vz3emByVtSmVVKToVUApxDouQ62zMCuPi"
}

###
// signup
POST http://localhost:4300/api/v1/gamer/signup
Content-Type: application/json

{
  "gamerTag": "Lamar",
  "email": "lamaranthonyholdings@gmail.com",
  "password": "12345678"
}

###
// verify email
POST http://localhost:4300/api/v1/email_verification/verify
Content-Type: application/json

{
  "email": "lamaranthonyholdings@gmail.com",
  "otp": "6133"
}

###
// login
POST http://localhost:4300/api/v1/gamer
Content-Type: application/json

{
  "gamerTag": "Vince",
  "password": "12345678"
}

###
// logout
POST http://localhost:4040/api/v1/gamer/logout
Content-Type: application/json

// password protected
###
GET http://localhost:4040/api/v1/gamer/protected
Content-Type: application/json

// forgot password
###
POST http://localhost:4300/api/v1/forgot_password/
Content-Type: application/json

{
  "email": "lamaranthonyholdings@gmail.com"
}


// password reset
###
POST http://localhost:4300/api/v1/forgot_password/reset
Content-Type: application/json

{
  "email": "lamaranthonyholdings@gmail.com",
  "otp": "3446",
  "newPassword": "12345678"
}

###

POST http://localhost:4300/api/v1/otp/request-new-otp
Content-Type: application/json

{
  "email": "lamaranthonyholdings@gmail.com"
}

###
// create token
POST http://localhost:4300/api/v1/token
Content-Type: application/json

{
    "address":"bRT1jCHNK5nb46R4tpkhgVX7GnwMTrSLZTfrxacpHACP",
    "uri":"https://virtronesports.com/img/IBFBelt.png",
    "symbol": "BNV",
    "name": "birtue",
    "mintAuthority": "7T6C4Es9QhcWMEVXvPpsnyzvrPj2SYUVvhgF49wRYg2e",
    "freezeAuthority": "7T6C4Es9QhcWMEVXvPpsnyzvrPj2SYUVvhgF49wRYg2e",
    "supply": "1000000000",
    "balance": "1000000000",
    "type": "Gaming Token"
  }

###
//creat a new account
POST http://localhost:4300/api/v1/account
Content-Type: application/json

###
// Auth route
GET http://localhost:4040/api/v1/gamer/authenticate
Content-Type: application/json


